name: Deployment Pipeline

on:
  push:
    branches: [main]

env:
  REPO_NAME: ${{ github.event.repository.name }}
  IMAGE_VERSION: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: 'Tag release'
        id: tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WITH_V: true

      - name: 'Login via Docker'
        uses: azure/docker-login@v1
        with:
          registry: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          ecr: 'false'
          logout: 'true'
          
      - run: |
          docker build . -t ${{ secrets.ACR_NAME }}/${{ env.REPO_NAME }}:${{ steps.tag.outputs.tag }}
          docker push ${{ secrets.ACR_NAME }}/${{ env.REPO_NAME }}:${{ steps.tag.outputs.tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        shell: bash

    steps:

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Deploy Container Instance"
        uses: azure/aci-deploy@v1
        with:
          location: eastus
          name: python-app
          resource-group: umGroupResource
          image: ${{ secrets.ACR_NAME }}/${{ env.REPO_NAME }}:${{ github.sha }}          
          dns-name-label: python-app-${{github.run_id}}-${{github.run_attempt}}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          ports: 6000
          cpu: 1
          memory: 1
        if: ${{steps.check_commit_message.outputs.action}} == *'deploy'*

      - name: "Logout"
        run: |
          az logout
        if: ${{steps.check_commit_message.outputs.action}} == *'deploy'*